core:
    opensky_credentials_path: .credentials.json
    location: Schiphol
    bbox_size: large

api:
    api_call_delay: 5.0

setup:
    max_windows: 1000
    display_name: HDMI-A-1

visuals:
    window_theme: aircraft
    window_size: miniature
    update_interval: 1.0
    tooltip_fields: [callsign, icao24, true_track, typecode]

tracking:
    icao24:
    callsign:
    airline:
    squawk:
    in_air:
    on_ground:
    arrival_airport:
    departure_airport:
    min_velocity:
    max_velocity:
    min_geo_altitude:
    max_geo_altitude:
    min_baro_altitude:
    max_baro_altitude:
    min_vertical_rate:
    max_vertical_rate:
    true_track_range:
    spi:
    sensors:
    category:
    origin_country:
    allowed_last_contact_lag:
    allowed_time_position_lag:
    model_name:
    wtc:
    wtg:
    typecode:
    manufacturer:
    description:
    engine_count:
    engine_type: